### ISSUE TITLE
Empty variable = empty css output

### ISSUE THREAD

**Issue by Jim-E** [oyejorge/less.php#145]
Try this:

Paste this into: http://lessphp.gpeasy.com/Demo

``` css
@width:auto;
@height:; // Notice, this variable is empty
#example{
  width:@width;
  height:@height;
}
```

Results;

``` css
#example {
  width: auto;
  height: ;  // notice, empty output
}
```

Is there a way to not have the empty output?

I ask this because I create variables from the database and sometimes they are empty.

Thanks
