### ISSUE TITLE
Import once doesn't work (implicitly or explicitly)

### ISSUE THREAD

**Issue by lazlo-bonin** [oyejorge/less.php#150]
I tried the following setup:

PHP:

``` php
$parser = new \Less_Parser();
$parser->parseFile('foo.less', '/');
echo $parser->getCss();
```

foo.less:

``` less
@import (once) 'bar.less';
@import (once) 'bar.less';

body { color: red; }
```

bar.less

``` less
body { color: blue; }
```

The output is:

``` css
body { color: blue; } 
body { color: blue; } 
body { color: red; }
```

`@import (once)` doesn't work. Also, [according to the doc](http://lesscss.org/features/#import-options-once), this should be a default behaviour, so just `@import` should be enough.
