### ISSUE TITLE
Global variable undefined when guard is used in mixin inside namespace

### ISSUE THREAD

**Issue by Roope** [oyejorge/less.php#151]
You can do this - simple guard:

``` less
@my-var: 666px;

.bar(@var:@my-var, @i:1) when (@i = 1) {
    div { width: @var; }
}

.bar();
```

And you can do this - mixin inside namespace, without guard:

``` less
@my-var: 666px;

#foo {
    .bar(@var:@my-var, @i:1) {
        div { width: @var; }
    }
}

#foo.bar();
```

But then you add guard back to the mixin:

``` less
@my-var: 666px;

#foo {
    .bar(@var:@my-var, @i:1) when (@i = 1) {
        div { width: @var; }
    }
}

#foo.bar();
```

..and it throws exception from Less.php line 7754:

```
exception 'Less_Exception_Compiler' with message 'variable @my-var is undefined in file ...
```

EDIT: here's the `compile` method where it actually comes from:
https://github.com/oyejorge/less.php/blob/master/lib/Less/Tree/Variable.php#L26
