### ISSUE TITLE
Output from @import (reference) triggered by :extend() and .mixin

### ISSUE THREAD

**Issue by Vovan-VE** [oyejorge/less.php#178]
Unexpected output goes from this code:

``` less
// lib.less

.mixin(@x) {
    mixed: @x;
}

.parent {
    .mixin(42);
    parent: 37;
}

.lorem:extend(.parent) {
}
.ipsum:extend(.parent) {
    a: b;
}

.dolor {
    .mixin(10);
}

.sit {
    b: c;
}

// -----------------------------

// main.less
@import (reference) "lib.less";

// empty result expected
```

Empty result is expected, but actual result is:

``` css
/* UNEXPECTED OUTPUT */
.lorem,
.ipsum {
  mixed: 42;
  parent: 37;
}
```

Less.php/1.7.0.2

Similar problem can be caught with `@import (reference) "bootstrap-3.2.0.less"; // EOF.` .
