### ISSUE TITLE
Wrong line number if LESS styles are located in the main LESS file

### ISSUE THREAD

**Issue by merszel** [oyejorge/less.php#192]
I am not sure if this is a bug or just a configuration issue.

Let's take a look on two examples:

1) We have a LESS file that is importing some other LESS files:

```less
@import "layout.less";
@import "navigation.less";
@import "modules.less";
```

If we create a source map then everything works fine. Web inspector shows the correct file and line number.

2) We have a LESS file that contains LESS styles and we do not import any other LESS file beside variables and mixins:

```less
@import "template_variables.less";
@import "bootstrap_variables.less";
@import "template_mixins.less";

#jm-footer-mod {
  padding-top: @JMbaseSpace;
  background: @JMfooterBackground;
  border-top: 1px solid @JMfooterBorder;
  color: @JMfooterFontColor;
  font-weight: @JMfootermodFontWeight;
  font-size: @JMfootermodFontSize;
  ul li {
    background-position: left 5px;
  }
}
#jm-footer-mod-in {
  border-bottom: 1px solid @JMfooterBorder;
}
#jm-footer {
  background: @JMfooterBackground;
  font-size: @JMfooterFontSize;
  line-height: @JMbaseLineHeight;
  padding: 25px 0;
  color: @JMfooterFontColor;
  font-weight: @JMfooterFontWeight;
}
#jm-copyrights {
  margin: 0;
}
```
If we create a source map and we will inspect for the #jm-footer-mod or #jm-footer or #jm-copyrights element then a web inspector will always show the style location as line number 1.

Does it mean that we need to import all LESS styles as separate files and the LESS styles cannot be located in the main file to get a web inspector to show a correct line number?

Just let me know if more info is needed.
