### ISSUE TITLE
Bug with nested mixin output

### ISSUE THREAD

**Issue by Roope** [oyejorge/less.php#20]
Hello!

Thanks for all your hard work with this one. Does the job very well and works very close to less.js like you promise - unlike many other php ports around there. Much appreciated!

Anyway I noticed small bug with variables when you create loop by guard and nested mixin like so:

``` css
.demo(@int) when (@int > 0) {
    .count-@{int} { 
        value: @int;
    }
    .demo(@int - 1);
}

.demo(3);
```

It compiles to:

``` css
.count-2 {
  value: 2;
}
.count-1 {
  value: 1;
}
.count-0 {
  value: 0;
}
```

when correct output should be:

``` css
.count-3 {
  value: 3;
}
.count-2 {
  value: 2;
}
.count-1 {
  value: 1;
}
```
