### ISSUE TITLE
calc(100% - 20px) is compiled into calc(80%) !

### ISSUE THREAD

**Issue by jaysee** [oyejorge/less.php#214]
hello,

as the title says, the following example is pre-calculated (good idea!), but wrongly!
```css
.test {
        width: calc(100% - 20px);
}
```
compils into 
```css
.test {
        width: calc(80%);
}
```

thanks
