### ISSUE TITLE
PHP setlocale changes parser output

### ISSUE THREAD

**Issue by Roope** [oyejorge/less.php#22]
Hello!

Found out (with percentage function) that decimal mark can change from point to comma. Here's a RTC:

``` php
setlocale(LC_ALL, 'fi_FI');

$less = new Less_Parser();

$less->parse("div { value: percentage(12.3 / 14.5); }");

echo $less->getCss();
```

output:

``` css
div { value: 84,82758620689656%; }
```
