### ISSUE TITLE
LESS plus selector

### ISSUE THREAD

**Issue by Altrowar** [oyejorge/less.php#261]
Hi!

I use the plus (+) selector as see as below:

```css
div {
 a,b {
   &+&{margin-top:0;} 
 }
}
```
...and I get this:
```css
div a + div a,
div a + div b,
div b + div a,
div b + div b {
  margin-top: 0;
}
```
but the property (working) code would be:
```css
div a + a,
div a + b,
div b + a,
div b + b {
  margin-top: 0;
}
```
King regards
