### ISSUE TITLE
"!important" applied to mixins is inconsistent

### ISSUE THREAD

**Issue by robertboloc** [oyejorge/less.php#269]
Hello,

First of all thank you for this library :)

I have noticed a strange behaviour when using `!important` on a mixin.

For example, the following less:
```less
.test {
  font-family: Arial;
  font-size: 15px;
  font-weight: bold;
}
.another {
  color: blue;
  .test() !important;
}
```
generates the css:
```less
.test {
  font-family: Arial;
  font-size: 15px;
  font-weight: bold;
}
.another {
  color: blue;
  font-family: Arial;
  font-size: 15px;
  font-weight: bold;
}
```
As we can see no `!important` statements have been applied to the contents
of the mixin.

If we change the less (sans-serif has been added to the font-family declaration):
```less
.test {
  font-family: Arial, sans-serif;
  font-size: 15px;
  font-weight: bold;
}
.another {
  color: blue;
  .test() !important;
}
```
we now get:
```less
.test {
  font-family: Arial, sans-serif;
  font-size: 15px;
  font-weight: bold;
}
.another {
  color: blue;
  font-family: Arial, sans-serif !important;
  font-size: 15px;
  font-weight: bold;
}
```
`!important` is applied to the font-family declaration.

From what I have been testing the `!important` statement is only applied when the css declaration has multiple words like `Aria, sans-serif` or `1px solid blue`, and only to the first statement of the mixin.

When applied to a mixin, the `!important` statment should be applied to all the declarations inside, as in the official library: http://goo.gl/kM81gj

So the end result should look like:
```less
.test {
  font-family: Arial;
  font-size: 15px;
  font-weight: bold;
}
.another {
  color: blue;
  font-family: Arial !important;
  font-size: 15px !important;
  font-weight: bold !important;
}
```

Thank you,
Rob
