### ISSUE TITLE
Undefined property: Less_Tree_Color::$value

### ISSUE THREAD

**Issue by gerardreches** [oyejorge/less.php#318]
I get an *Undefined property: Less_Tree_Color::$value* exception with this code:

```less
@black: #000000;
@white: #ffffff;
@color_list: black, white;

.generate-color-system(length(@color_list));

.generate-color-system(@number, @i: 1) when (@i =< @number) {
	@name: extract(@color_list, @i);

	.bg-@{name} { background-color: @@name; }

	.generate-color-system(@number, (@i + 1));
}
```

This code is compiled correctly at [lesscss.org demo](http://lesscss.org/less-preview/#{%22less%22%3A%22%40black%3A%20%23000000%3B\n%40white%3A%20%23ffffff%3B\n%40color_list%3A%20black%2C%20white%3B\n\n.generate-color-system%28length%28%40color_list%29%29%3B\n\n.generate-color-system%28%40number%2C%20%40i%3A%201%29%20when%20%28%40i%20%3D%3C%20%40number%29%20{\n\t%40name%3A%20extract%28%40color_list%2C%20%40i%29%3B\n\n\t.bg-%40{name}%20{%20background-color%3A%20%40%40name%3B%20}\n\n\t.generate-color-system%28%40number%2C%20%28%40i%20%2B%201%29%29%3B\n}%22}) but not in my project and neither on [less.php demo](http://lessphp.typesettercms.com/Demo) (here it throws *variable @ is undefined*).

Am I missing something? Is there a workaround?

EDIT:
If I change `background-color: @@name;` to `background-color: @name;` it works on less.php but not in Less.
