### ISSUE TITLE
Parse error on CSS grid template with named lines or minmax function, but not both

### ISSUE THREAD

**Issue by Celti** [oyejorge/less.php#359]
This is a bit of a weird one. I'm building a CSS grid layout, starting with this bit of LESS:

```less
#dokuwiki__site {
    display: grid;
    box-sizing: border-box;
    width: 100vw;
    height: 100vh;
    grid-template-rows:
        [header] 2em
        [content] 1fr
        [footer] 2em;
    grid-template-columns:
        [left] minmax(auto, min-content)
        [center] auto
        [right] minmax(auto, min-content);
    grid-gap: 1px;
}
```

That code gives a parse error on the `grid-template-columns` property. That parse error disappears if I remove *either* the grid line names, e.g.:
```
        [left] minmax(auto, min-content)
        [center] auto
        [right] minmax(auto, min-content);
```
...*or* if I remove the use of the CSS `minmax()` function, e.g.:
```
    grid-template-columns:
        [left] auto
        [center] auto
        [right] auto;
```
Neither option, of course, is quite what I want. `less.js` compiles all three just fine.
