### ISSUE TITLE
[BUG] Variable not found in second level of import directive

### ISSUE THREAD

**Issue by francoispluchino** [oyejorge/less.php#53]
Since this commit c4abe465bf62d46e238fb36393b82f084213ec29 (between `v1.5.1.1` and `v1.5.1.2`), the variables defined in the master Less file are not correctly transfered in the import directive of the imported Less file (only variable with absolute path).

Example:

``` css
# style.less
@path: 'test';

@import "@{path}/variables.less";

body {
    background-color: @body-bg;
    color:            @color;
}
```

``` css
# test/variables.less
@import "@{path}/foobar.less";

@color: #000;
```

``` css
# test/foobar.less
@body-bg: #fff;
```

This example works correctly with the relative path, but an Less_Exception_Parser `File '@{path}/foobar.less' not found.` is thrown when the variable is a absolute path: `@path: "c:/test";` on `style.less` file.

This example works correctly with absolute path before this commit c4abe465bf62d46e238fb36393b82f084213ec29, but also with the official version of [Less.js](http://www.lesscss.org) or the [WinLess](http://winless.org/) utility.

I suppose the current directory of the imported file is added to the absolute path defined in the variable:
`@path: "c:/test";` devient `@path: "c:/testc:/test";` dans `test/variables`.
