### ISSUE TITLE
Compiler broken in 1.6.1

### ISSUE THREAD

**Issue by zghosts** [oyejorge/less.php#63]
In version 1.6.1 the following less code compiles incorrectly:

``` less
.foo {
    h2,h3 {
        font-size: 15px;
    }
}
```

it compiles to

``` css
.foo h2,
.fooh3 {
  font-size: 15px;
}
```

Where it should compile to

``` css
.foo h2,
.foo h3 {
  font-size: 15px;
}
```

in 1.5.1.1 it works correctly
