### ISSUE TITLE
Relative paths resolved incorrectly

### ISSUE THREAD

**Issue by caufang** [oyejorge/less.php#72]
Ran into a bug while testing this library with the Drupal module. This isn't a bug in the module as this problem does not present itself with the https://github.com/leafo/lessphp library, nor with the upcoming lessjs server side support.

file structure in directory "/sites/all/modules/less/less_demo/":

```
/images/
/images/logo.png
/styles/
/styles/info.less
```

info.less:

``` css
.less_demo_logo {
  background: transparent url(../images/logo.png) center center no-repeat;
}
```

expected output:

``` css
.less_demo_logo {
  background: transparent url(/sites/all/modules/less/less_demo/images/logo.png) center center no-repeat;
}
```

actual output:

``` css
.less_demo_logo {
  background: transparent url(/sites/all/modules/less/less_demo/styles/images/logo.png) center center no-repeat;
}
```

I tried to debug the problem in the source but couldn't grok the whole code base to be sure as to the cause.

I think it has to do with path normalization.

in /lib/Less/Tree/Url.php

``` php
            // Add the base path if the URL is relative
            if( Less_Parser::$options['relativeUrls']
                && $this->currentFileInfo
                && is_string($val->value)
                && Less_Environment::isPathRelative($val->value)
            ){
                $rootpath = $this->currentFileInfo['uri_root'];
                if ( !$val->quote ){
                    $rootpath = preg_replace('/[\(\)\'"\s]/', '\\$1', $rootpath );
                }
                $val->value = $rootpath . $val->value;
            }

```

It seems like the above breaks it for me. I removed it and it appears to fix the problem.

I think this chunk of code was also adding an erroneous slash that call to Less_Environment::normalizePath() was then stripping the relative-ness of the path.

btw, in Less_Environment::normalizePath() it might be a good idea to add this at the start.

``` php
$path = preg_replace('/([^:])(\/+)/', '$1/', $path);
```

this will remove any double slashes that don't immediately follow a colon since browsers/servers interpret them as a single slash.

Sorry I didn't make this into a pull request, didn't have the time to setup a local copy.
